apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: sol-panel
    component: frontend
spec:
  selector:
    matchLabels:
      app: sol-panel
      component: frontend
  template:
    metadata:
      labels:
        app: sol-panel
        component: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "postgresql://solpanel:thisisnotsecure@{{ .Release.Name }}-postgresql:5432/solpanel?schema=public"
            - name: REDIS_URL
              value: "redis://{{ .Release.Name }}-redis-master:6379"
