apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sol-panel.fullname" . }}
  labels:
    {{- include "sol-panel.labels" . | nindent 4 }}
    component: frontend
spec:
  selector:
    matchLabels:
      {{- include "sol-panel.selectorLabels" . | nindent 6 }}
      component: frontend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sol-panel.selectorLabels" . | nindent 8 }}
        component: frontend
    spec:
      serviceAccountName: {{ include "sol-panel.serviceAccountName" . }}
      containers:
        - name: frontend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "postgresql://solpanel:thisisnotsecure@{{ .Release.Name }}-postgresql:5432/solpanel?schema=public"
            - name: REDIS_URL
              value: "redis://{{ .Release.Name }}-redis-master:6379"
