# fly.toml app configuration file generated for sol-panel on 2023-06-19T11:05:07-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sol-panel"
primary_region = "mia"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
