apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sol-panel-deployer
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "sol-panel.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role 
  name: solpanel-deploy
  apiGroup: rbac.authorization.k8s.io