#!/bin/sh

[ "$SKIP_HUSKY" = "true" ] && exit 0

. "$(git rev-parse --show-toplevel)/.husky/_/husky.sh"



echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
pnpm run check:format ||
(
    echo '
    🤢🤮🤢🤮 Its F*&CK*NG RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run `pnpm format`, add changes and try commit again.
';
    false;
)

# Check ESLint Standards
pnpm run check:lint ||
(
        echo '
        😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.\r\n'
        false; 
)

# Check tsconfig standards
pnpm run check:types ||
(
    echo '
    🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.
'
    false;
)

# Check prisma 
pnpm prisma validate

# If everything passes... Now we can try to build
echo '
🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔
'

# If everything passes... Now we can commit
echo '
✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅
'
