name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - main
      - next

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20.2
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: corepack pnpm install

      - name: Run tests
        run: corepack pnpm test
