name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - main
      - next

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: pnpm install
      - name: Run tests
        run: pnpm test
